# Generated by Django 6.0.5 on 2026-05-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
